feat: 포토스팟 생성, 수정, 삭제, 상세 보기 구현
chalkak2023/Chalkak-Frontend pull request #13
Opened 2023-03-04 08:31 UTC by muja-code

### PR 타입(하나 이상의 PR 타입을 선택)
- [x] 기능 추가   
- [x] 기능 수정   
- [ ] 기능 삭제   
- [ ] 버그 수정   

### 변경 사항
- resolve #12
- resolve #11
- resolve #10
- 포토스팟 생성, 수정, 삭제, 상세 보기 구현

### 테스트 결과
- 정상

2023-03-04 10:12 UTC, cchoseonghun requested changes
- import에서 안쓰는 (회색처리) 부분은 정리 필요.
- 포토스팟 저장 안되는 문제로 수정 등 다른 코드 리뷰는 못한 상태

2023-03-04 10:12 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotCreateModal.js
> +          <Button variant="primary" onClick={() => {createPhotospot(title, description, imageFile, state.photospotSlice.lat, state.photospotSlice.lng);}}>
createPhotospot 함수의 인자로 전달할 필요 없이 함수 안에서 그냥 가져다 쓰면 되보임

2023-03-04 10:12 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotCreateModal.js
> +  function createPhotospot(title, description, imageFile, lat, lng) {
빈 값일 경우에 대한 체크 간단하니까 추가하면 좋아보입니다.

2023-03-04 10:12 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotCreateModal.js
> +  function createPhotospot(title, description, imageFile, lat, lng) {
제목, 내용, 사진까지 담았는데 400 에러를 받으며 저장이 안되고 있습니다. 어떤 문제가 있는걸까요? 
이미지 파일은 jpg, png 시도해봄

<img width="1280" alt="스크린샷 2023-03-04 오후 7 09 24" src="https://user-images.githubusercontent.com/109499274/222894022-e69f5519-1544-4c42-aa83-f1a6d4f5e139.png">

2023-03-04 13:32 UTC, muja-code commented on src/App.js
> +        <Route path="/photospot" element={<Photospot />}></Route>
포토스팟 수정이나 생성하는 페이지와 포토스팟을 확인하는 페이지는
콜렉션을 누르면 페이지 보여주는 부분이라 일부러 네비게이션에 안 넣었는데 개발단계에는 넣어둘까요?

2023-03-04 16:03 UTC, muja-code commented on src/routes/Photospot/Photospot.js
> +  function clickMarker(modalName, lat, lng) {
photospot 생성, 수정 페이지 부분은 로그인이 안되어있으면 접근을 못하게 하는 방향으로 해보겠습니다

2023-03-04 17:07 UTC, cchoseonghun commented on src/App.js
> +        <Route path="/photospot" element={<Photospot />}></Route>
네 샘플페이지 처럼 임시로 넣어두면 좋을 것 같아요.
대신 콜렉션 페이지가 생기면 오히려 바로 포토스팟 가는 과정에서 에러가 날듯하니 그 땐 빼면 될 것 같습니다.

2023-03-04 17:07 UTC, cchoseonghun commented on src/routes/Photospot/Photospot.js
> +  function clickMarker(modalName, lat, lng) {
해보겠다는게 이번 pr에 적용할거란 건가요 아니면 추후 추가할 예정인건가요?

2023-03-05 01:26 UTC, muja-code commented on src/routes/Photospot/Photospot.js
> +  function clickMarker(modalName, lat, lng) {
이번 PR에 적용할 생각입니다

2023-03-05 07:27 UTC, tstunas requested changes
클라이언트에서 테스트할 때 임의로 collecitonId가 1인 경우로 api를 날리는데, 이 경우에 그 컬렉션이 존재하는지 존재하지 않는지를 검사하지 않고 있습니다. 그 결과, 콜렉션 테이블에 id가 1인 데이터가 없을 경우에 외래키 제약으로 존재하지 않는 콜렉션을 참고하는 에러가 납니다.

2023-03-05 09:51 UTC, cchoseonghun approved these changes
직접 테스트 했을 때 이미지 업로드 안되던 문제도 수정되어 잘 되네요.
다만 코드상으로 체크하면 좋겠는 것들 리뷰 달았으니 확인해보시고
문제 없다면 직접 resolve 하여 merge 진행하시면 될 것 같습니다.

2023-03-05 09:51 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotModifyModal.js
> +  const [description, setDescription] = useState(state.photospotSlice.photospot.description);
이런 사용 방식 때문인지 포토스팟편집 메뉴에서 여러 등록된 포토스팟에 대해 왔다갔다 누르면 
해당 포토스팟 내용이 아닌 이전 포토스팟 내용으로 보이는 버그가 있네요.
redux 데이터를 useState에 넣어서 사용하는게 아닌
해당 input value에 그냥 
```
<input value={state.photospotSlice.photospot.title} />
```
과 같이 작성하여 위 문제를 해결할 수 있겠네요.

대신 이 경우 onChange에 해당되지 않아 수정사항 없이 수정 버튼을 누르게 되면 빈 값이 전달될텐데 
onChange를 통해 value 값을 얻는게 아닌 
예전처럼 document.querySelector()를 써야 될 것으로 보입니다.

2023-03-05 09:51 UTC, cchoseonghun commented on src/store/photospot.slice.js
> +let photospotSlice = createSlice({
물론 정답은 없겠지만 리액트 사용하면서 이게 이름이 길면
부를 때 불편하더라구요. 
무현님도 state.photospotSlice.photospot 과 같은 방식으로 부르느라 힘들었을 것 같은데
만약 안에 데이터와 같은 이름인 photospot 때문이라면
저 같은 경우는 photospot을 data로 짓고
photoSlice 를 photospot으로 지을 것 같아요.
그렇다면
state.photospot.data 와 같이 짧아지겠네요.

2023-03-05 09:51 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotDetailModal.js
> +          <img src={state.photospotSlice.photospot.imagePath}></img>
여기도 이미지에 대한 크기 조정이 들어가면 좋을 것 같습니다.

2023-03-05 09:51 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotCreateModal.js
> +  const [photospotEmptyShow, setPhotospotEmptyShow] = useState(true)
photospotEmptyShow 보단 isPhotospotEmpty
또는 해당 에러 내용에 맞게
isEmptyValue
라는 변수명이 더 적절하지 않나 의견 내봅니다.

2023-03-05 09:51 UTC, cchoseonghun commented on src/routes/Photospot/PhotospotCreateModal.js
> +      },
axios는 formdata에 대한 headers 지정을 따로 안해줘도 작동하는걸로 알고 있는데 한번 테스트 해보시길 바랍니다. 
저도 없이 잘 했던 기억이 있네요.

2023-03-05 10:40 UTC, tstunas approved these changes

2023-03-05 15:51 UTC, merged