feat: 회원이 접근가능한 API에 요청 보낼 때 쓸 AxiosInstance 구현
chalkak2023/Chalkak-Frontend pull request #8
Opened 2023-03-03 05:38 UTC by tstunas

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가   
- [ ] 기능 수정   
- [ ] 기능 삭제   
- [ ] 버그 수정   
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 변경 사항
- resolve #6
- 기존에 사용하던 axios를 대체하여 사용할 수 있는 userApiAxios 객체를 export.
- userApiAxios는 기본 설정으로 api url prefix를 'http://localhost:8080/api'로 설정하여, 주소는 /auth/signin 처럼 간략하게 쓸 수 있음.
- withCredentials을 true로 설정하고 있어서, userApiAxios를 사용하면 한 번 더 쓰지 않아도 됨.

### 참고사항
- 관리자는 따로 토큰들이 있으므로 관리자 API는 전용 AxiosInstance를 따로 만들어야함.
- /auth/signin처럼 간략하게 쓸수도 있지만 full url 써도 에러는 안 남.

2023-03-03 05:53 UTC, tstunas commented
잠시 문제가 있어서 닫음

2023-03-03 08:05 UTC, tstunas commented
로그아웃 버튼에 리프레시 토큰을 통한 재발급 후 재시도 적용

2023-03-03 16:43 UTC, cchoseonghun requested changes
리뷰로 적은 피드백에 대한 수정 필요

2023-03-03 16:43 UTC, cchoseonghun commented on src/routes/components/NavSideBar.js
> -import { setUser } from '../../store/user.slice';
해당 부분 필요한 부분인데 userApiAxios를 import하며 덮어씌워진듯 합니다.

2023-03-03 16:43 UTC, cchoseonghun commented on src/utils/user-api-axios.js
> +  baseURL: "http://localhost:8080/api",
추후 admin 기능도 붙을걸 위해 /api 까지 baseURL로 하기보단 http://localhost:8080 까지 하는게 좋아보입니다.
admin 은 http://localhost:8080/api가 아닌 http://localhost:8080/admin 이 될거니까요.

2023-03-03 16:43 UTC, cchoseonghun commented on src/utils/user-api-axios.js
> +  baseURL: "http://localhost:8080/api",
수정된다면 아래 admin 관련 코드들도 같이 수정 부탁드립니다.

2023-03-04 01:32 UTC, tstunas commented on src/utils/user-api-axios.js
> +  baseURL: "http://localhost:8080/api",
확인했습니다. 민주님 admin 쪽 코드 보고 그쪽도 추가하겠습니다.

2023-03-04 01:33 UTC, tstunas commented on src/routes/components/NavSideBar.js
> -import { setUser } from '../../store/user.slice';
아 어쩌다가 삭제된 상태로 커밋된 모양이네요. 추가하겠습니다.

2023-03-04 03:26 UTC, tstunas commented on src/routes/components/NavSideBar.js
> -import { setUser } from '../../store/user.slice';
다시 복구했습니다.

2023-03-04 03:26 UTC, tstunas commented on src/utils/user-api-axios.js
> +  baseURL: "http://localhost:8080/api",
확장했습니다.

2023-03-04 04:49 UTC, cchoseonghun approved these changes
확인

2023-03-04 06:27 UTC, merged